version: '3.8'
services:
  mysql:
    container_name: 'simple-blog-rest-api-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=simple-blog'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=callum'
    ports:
      - '3306:3306'
  app:
    container_name: 'simple-blog-app'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/simple-blog
      SPRING_DATASOURCE_USERNAME: callum
      SPRING_DATASOURCE_PASSWORD: secret
