services:
  mysql:
    container_name: 'simple-blog-rest-api-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=simple-blog'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=callum'
    ports:
      - '3306:3306'
